# -*- coding: utf-8 -*-
"""weather-api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgFCg_KvWjcmpi6anv7qJhT8ztnJa67P

# **Load the Data Frame**
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/data/TG_STAID000001.txt", skiprows=20, parse_dates=["    DATE"])

df

"""##**Show Certains Rows**"""

df[10:20]

"""## **Show Certains Columns**"""

df.columns

# One colum
df['   TG']

#multiple colum
df[['    DATE', '   TG',]]

"""## **Simple Statistics a bout the data and filtering**"""

#df.loc[condition]
df.loc[df['   TG']!= -9999]['   TG'].mean()/10

df.loc[df['   TG']!= -9999]['   TG'].max()/10

df.loc[df['   TG']!= -9999]['   TG'].min()/10

df.loc[df['   TG']!= -9999]['   TG'].hist()

df

df.loc[df['    DATE'] == "1860-01-05"]['   TG'].squeeze()/10

df.loc[df['   TG'] == df['   TG'].max()]['    DATE'].squeeze()

df.loc[3, '   TG']

import numpy as np

df["TG0"] = df['   TG'].mask(df['   TG'] == -9999, np.nan)

df.columns
df

"""## **Calculate a New Colum out of Existing column**"""

df["TG"] = df["TG0"]/10

df.columns
df



df["Farenheith"] = df["TG"] * (9/5) + 32

df

df["TG"].hist()

df[100:1000].plot(x='    DATE', y="TG", figsize=(15,3))

